name: Conditional job steps

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/python-dummy-app
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect job vars
        id: vars
        run: |
          true && echo "status_1=" >> $GITHUB_OUTPUT; fi
          false && echo "status_2=" >> $GITHUB_OUTPUT; fi

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          tags: |
#            ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}


#      - name: Do something 1
#        if: steps.vars.outputs.status_1
#        run: |
#          echo "status_1=${{ steps.vars.outputs.status_1 }}"
#
#      - name: Do something 2 (actually should be skipped)
#        if: steps.vars.outputs.status_2 != ''
#        run: |
#          echo "status_2=${{ steps.vars.outputs.status_2 }}"