name: If

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Collect job vars
        id: vars
        run: |
          echo "this_var_set_to_true=true" >> "$GITHUB_OUTPUT"
          echo "this_var_set_to_false=false" >> "$GITHUB_OUTPUT"
          echo "this_var_set_to_empty=" >> "$GITHUB_OUTPUT"
          echo "this_var_set_to_ok=ok" >> "$GITHUB_OUTPUT"
          echo "this_var_set_to_1=1" >> "$GITHUB_OUTPUT"
          echo "this_var_set_to_0=0" >> "$GITHUB_OUTPUT"

      - name: Check 'this_var_set_to_true'
        if: steps.vars.outputs.this_var_set_to_true
        run: echo "::notice::Check 'this_var_set_to_true'"

      - name: Check 'this_var_set_to_false'
        if: steps.vars.outputs.this_var_set_to_false
        run: echo "::notice::Check 'this_var_set_to_false'"

      - name: Check 'this_var_set_to_empty'
        if: steps.vars.outputs.this_var_set_to_empty
        run: echo "::notice::Check 'this_var_set_to_empty'"

      - name: Check 'this_var_set_to_ok'
        if: steps.vars.outputs.this_var_set_to_ok
        run: echo "::notice::Check 'this_var_set_to_ok'"

      - name: Check 'this_var_set_to_1'
        if: steps.vars.outputs.this_var_set_to_1
        run: echo "::notice::Check 'this_var_set_to_1'"

      - name: Check 'this_var_set_to_0'
        if: steps.vars.outputs.this_var_set_to_0
        run: echo "::notice::Check 'this_var_set_to_0'"

      - name: Check non-existent variable
        if: steps.vars.outputs.this_var_is_not_set
        run: echo "::notice::Check non-existent variable"