name: Conditional Steps Workflow

on:
  workflow_dispatch:
    inputs:
      run_step1:
        description: 'Step 1'
        required: true
        default: true
        type: boolean
      run_step2:
        description: 'Step 2'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        if: ${{ github.event.inputs.run_step1 == 'true' }}
        run: echo "Step 1"

      - name: Step 2
        if: ${{ github.event.inputs.run_step2 == 'true' }}
        run: echo "Step 2"