name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected:
        description: ''
        required: true
        default: ''
        type: choice
        options:
          - ''
          - 'All'
          - 'company-001'
          - 'company-002'
          - 'company-003'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        run: echo "Checkout"


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-002',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-003',  title: 'Company-003', logo: 'logo003.png' }

    name: Deploy for ${{ matrix.company.title }}

    steps:
      - name: Set do-not-skip and other vars
        id: vars
        if: ${{ github.event.inputs.selected == 'All' || github.event.inputs.selected == matrix.company.id }}
        run: |
            echo "::notice::Running deployment for ${{ matrix.company.title  }}"
            echo "do_not_skip=true" >> "$GITHUB_OUTPUT"

      - name: Do something 1
        if: steps.vars.outputs.do_not_skip
        run: echo "Hello world 1"

      - name: Do something 2
        if: steps.vars.outputs.do_not_skip
        run: echo "Hello world 2"