name: Matrix-2

on:
  workflow_dispatch:

env:
  MATRIX: "Hello world"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checkout"

      - name: Test
        run: |
          echo "test=${{ env. MATRIX }}"