name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected:
        description: "Select a company.\n Leave empty to run all jobs."
        required: false
        default: ""
        type: choice
        options: [
          'company-001',
          'company-002',
          'company-003',
        ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-001',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-001',  title: 'Company-003', logo: 'logo003.png' }

    name: Build for ${{ matrix.company.title }}

    steps:
      - name: Check if company is selected
        id: check_selection
        run: |
          selected="${{ github.event.inputs.selected }}"
          if [[ -z "$selected" ]]; then
            echo "Running all jobs."
            echo "skipped=false" >> "$GITHUB_OUTPUT"
          elif [[ "$selected" == "${{ matrix.company.id }}" ]]; then
            echo "Running job for company ID: ${{ matrix.company.id }}"
            echo "skipped=false" >> "$GITHUB_OUTPUT"
          else
            echo "id not found"
            exit 1
          fi

      - name: Mark as skipped
        if: ${{ steps.check_selection.outputs.skipped == 'true' }}
        run: |
          echo "::notice::Job for company ID ${{ matrix.company.id }} was skipped."