name: Matrix with two jobs

on:
  workflow_dispatch:

env:
  MATRIX: |
    [
      {"id": "company-001", "title": "Company-001", "logo": "logo001.png"},
      {"id": "company-002", "title": "Company-002", "logo": "logo002.png"},
      {"id": "company-003", "title": "Company-003", "logo": "logo003.png"}
    ]

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: build-matrix
        run: echo "matrix=${MATRIX}" >> "$GITHUB_OUTPUT"

  deploy-one:
    needs: [ config ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        company: ${{ fromJSON(needs.config.outputs.matrix) }}
    environment: deploy-one
    steps:
      - run: |
          echo "Deploying for company ID: ${{ matrix.company.id }}"
          echo "Company Title: ${{ matrix.company.title }}"
          echo "Company Logo: ${{ matrix.company.logo }}"
