name: Matrix with two jobs

on:
  workflow_dispatch:

env:
  MATRIX: |
    {
      "company": [
        {"id": "company-001", "title": "Company-001", "logo": "logo001.png" },
        {"id": "company-002", "title": "Company-002", "logo": "logo002.png" },
        {"id": "company-003", "title": "Company-003", "logo": "logo003.png" }
      ]
    }

jobs:
  deploy-one:
    runs-on: ubuntu-latest
    environment: deploy-one
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(env.MATRIX) }}
    steps:
      - run: echo "111"

  deploy-all:
    runs-on: ubuntu-latest
    environment: deploy-all
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(env.MATRIX) }}
    steps:
      - run: echo "222"