name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected_companies:
        description: 'Enter company IDs separated by commas (e.g., 1,3,7). Leave empty to run all jobs.'
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 1,  title: "Company-001", logo: "logo001.png", url: "https://company-001.com" }
          - { id: 2,  title: "Company-002", logo: "logo002.png", url: "https://company-002.com" }
          - { id: 3,  title: "Company-003", logo: "logo003.png", url: "https://company-003.com" }
          - { id: 4,  title: "Company-004", logo: "logo004.png", url: "https://company-004.com" }
          - { id: 5,  title: "Company-005", logo: "logo005.png", url: "https://company-005.com" }
          - { id: 6,  title: "Company-006", logo: "logo006.png", url: "https://company-006.com" }
          - { id: 7,  title: "Company-007", logo: "logo007.png", url: "https://company-007.com" }
          - { id: 8,  title: "Company-008", logo: "logo008.png", url: "https://company-008.com" }
          - { id: 9,  title: "Company-009", logo: "logo009.png", url: "https://company-009.com" }
          - { id: 10, title: "Company-010", logo: "logo010.png", url: "https://company-010.com" }
          - { id: 11, title: "Company-011", logo: "logo011.png", url: "https://company-011.com" }
          - { id: 12, title: "Company-012", logo: "logo012.png", url: "https://company-012.com" }
          - { id: 13, title: "Company-013", logo: "logo013.png", url: "https://company-013.com" }
          - { id: 14, title: "Company-014", logo: "logo014.png", url: "https://company-014.com" }
          - { id: 15, title: "Company-015", logo: "logo015.png", url: "https://company-015.com" }

    name: Build for ${{ matrix.company.title }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check if company is selected
        id: check_selection
        run: |
          selected_companies="${{ github.event.inputs.selected_companies }}"
          if [[ -z "$selected_companies" ]]; then
            echo "Running all jobs."
            echo "skipped=false" >> "$GITHUB_OUTPUT"
          elif [[ ",$selected_companies," != *",${{ matrix.company.id }},"* ]]; then
            echo "Skipping job for company ID: ${{ matrix.company.id }}"
            echo "skipped=true" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "Running job for company ID: ${{ matrix.company.id }}"
            echo "skipped=false" >> "$GITHUB_OUTPUT"

      - name: Mark as skipped
        if: ${{ steps.check_selection.outputs.skipped == 'true' }}
        run: |
          echo "::notice::Job for company ID ${{ matrix.company.id }} was skipped."