name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected:
        description: ''
        required: true
        default: ''
        type: choice
        options:
          - ''
          - 'All'
          - 'company-001'
          - 'company-002'
          - 'company-003'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout
        run: echo "Checkout"

      - name: Log in to Docker Hub
        run: echo "Log in to Docker Hub"

      - name: Collect job vars
        id: vars
        run: echo "image_not_in_registry=true" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        if: steps.vars.outputs.image_not_in_registry
        run: echo "Set up Docker Buildx"

      - name: Build and push
        if: steps.vars.outputs.image_not_in_registry
        run: echo "Build and push"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-002',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-003',  title: 'Company-003', logo: 'logo003.png' }

    name: Deploy for ${{ matrix.company.title }}

    steps:
      - name: Do something 1
        if: ${{ github.event.inputs.selected  == 'All' || github.event.inputs.selected == matrix.company.id }}
        run: echo "Hello world 1"

      - name: Do something 2
        if: ${{ github.event.inputs.selected  == 'All' || github.event.inputs.selected == matrix.company.id }}
        run: |
          echo "Hello world 2"
         
