name: Matrix-2

on:
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      company: ${{ steps.vars.outputs.company }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Collect workflow vars
        id: vars
        run: |
          printenv
          echo 'company=123>> "$GITHUB_OUTPUT"

  deploy:
    needs: [config]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "test=${{ needs.config.outputs.company }}"