name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected:
        description: 'Select a company or leave empty to run all jobs.'
        required: false
        default: ''
        type: choice
        options: [
          '',
          'company-001',
          'company-002',
          'company-003',
        ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-002',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-003',  title: 'Company-003', logo: 'logo003.png' }

    name: Build for ${{ matrix.company.title }}

    steps:
      - name: Collect job vars
        id: vars
        run: |
          selected="${{ github.event.inputs.selected }}"
          if [[ -z "$selected" ]]; then
            echo "Running all jobs."
            echo "::notice::Run job for: ${{ matrix.company.id }}"
            echo "do_not_skip=true" >> "$GITHUB_OUTPUT"            
          elif [[ "$selected" == "${{ matrix.company.id }}" ]]; then
            echo "Running job for: ${{ matrix.company.id }}"
            echo "::notice::Run job for: ${{ matrix.company.id }}"
            echo "do_not_skip=true" >> "$GITHUB_OUTPUT"            
          else
            echo "Skipping job for: ${{ matrix.company.id }}"
            echo "::warning::Skip job for: ${{ matrix.company.id }}"
            echo "do_not_skip=false" >> "$GITHUB_OUTPUT"            
          fi

      - name: Do something 1
        if: steps.vars.outputs.do_not_skip == 'true'
        run: echo "Hello world 1"

      - name: Do something 2
        if: steps.vars.outputs.do_not_skip == 'true'
        run: echo "Hello world 2"
