name: Matrix-2

on:
  workflow_dispatch:
    inputs:
      selected:
        description: ''
        required: true
        default: ''
        type: choice
        options:
          - ''
          - 'All'
          - 'company-001'
          - 'company-002'
          - 'company-003'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checkout"

  deploy-one:
    if: github.event.inputs.selected != 'All'
    runs-on: ubuntu-latest
    needs: [ build ]
    name: Deploy for ${{ github.event.inputs.selected }}
    steps:
      - name: Do something 1
        run: echo "Hello world 1"

  deploy-all:
    if: github.event.inputs.selected == 'All'
    runs-on: ubuntu-latest
    needs: [ build ]
    name: Deploy all
    steps:
      - name: Do something 1
        run: echo "Hello world 1"