name: Matrix

on:
  workflow_dispatch:
    inputs:
      selected:
        description: 'Enter a company ID (e.g., `1`). Leave empty to run all jobs.'
        required: false
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 1,  title: "Company-001", logo: "logo001.png" }
          - { id: 2,  title: "Company-002", logo: "logo002.png" }
          - { id: 3,  title: "Company-003", logo: "logo003.png" }
          - { id: 4,  title: "Company-004", logo: "logo004.png" }
          - { id: 5,  title: "Company-005", logo: "logo005.png" }
          - { id: 6,  title: "Company-006", logo: "logo006.png" }
          - { id: 7,  title: "Company-007", logo: "logo007.png" }
          - { id: 8,  title: "Company-008", logo: "logo008.png" }
          - { id: 9,  title: "Company-009", logo: "logo009.png" }
          - { id: 10, title: "Company-010", logo: "logo010.png" }
          - { id: 11, title: "Company-011", logo: "logo011.png" }
          - { id: 12, title: "Company-012", logo: "logo012.png" }
          - { id: 13, title: "Company-013", logo: "logo013.png" }
          - { id: 14, title: "Company-014", logo: "logo014.png" }
          - { id: 15, title: "Company-015", logo: "logo015.png" }

    name: Build for ${{ matrix.company.title }}

    steps:
      - name: Check if company is selected
        id: check_selection
        run: |
          selected="${{ github.event.inputs.selected }}"
          if [[ -z "$selected" ]]; then
            echo "Running all jobs."
            echo "skipped=false" >> "$GITHUB_OUTPUT"
          elif [[ "$selected" == "${{ matrix.company.id }}" ]]; then
            echo "Running job for company ID: ${{ matrix.company.id }}"
            echo "skipped=false" >> "$GITHUB_OUTPUT"
          else
            echo "Skipping job for company ID: ${{ matrix.company.id }}"
            echo "skipped=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Mark as skipped
        if: ${{ steps.check_selection.outputs.skipped == 'true' }}
        run: |
          echo "::notice::Job for company ID ${{ matrix.company.id }} was skipped."