name: Matrix-2

on:
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.vars.outputs.matrix }}
    env:
      AAA: 'aaaaaaa'

    steps:
      - name: Collect workflow vars
        id: vars
        run: |
          echo "aaa=$AAA"
          echo 'matrix=123' >> "$GITHUB_OUTPUT"

  deploy:
    needs: [config]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "test=${{ needs.config.outputs.matrix }}"