name: Matrix with two jobs

on:
  workflow_dispatch:
    inputs:
      selected:
        description: ''
        required: true
        default: ''
        type: choice
        options:
          - ''
          - 'All'
          - 'company-001'
          - 'company-002'
          - 'company-003'

env:
  MATRIX: |
    [
      {"id": "company-001", "title": "Company-001", "logo": "logo001.png"},
      {"id": "company-002", "title": "Company-002", "logo": "logo002.png"},
      {"id": "company-003", "title": "Company-003", "logo": "logo003.png"}
    ]

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: build-matrix
        run: |
          echo "matrix=$(echo "${MATRIX}" | jq -c '.')" >> "$GITHUB_OUTPUT"

  deploy-one:
    if: github.event.inputs.selected != "All"
    needs: [ config ]
    runs-on: ubuntu-latest
    environment: deploy-one
    strategy:
      matrix:
        company: ${{ fromJSON(needs.config.outputs.matrix) }}
    name: Deploy for ${{ github.event.inputs.selected }}
    steps:
      - name: Set do-not-skip and other vars
        id: vars
        if: github.event.inputs.selected == matrix.company.id
        run: |
          echo "::notice::Running deployment for ${{ matrix.company.title  }}"
          echo "do_not_skip=true" >> "$GITHUB_OUTPUT"
      - name: Deploy
        if: steps.vars.outputs.do_not_skip
        run: |
          echo "ID: ${{ matrix.company.id }}"
          echo "Company Title: ${{ matrix.company.title }}"
          echo "Company Logo: ${{ matrix.company.logo }}"

  deploy-all:
    if: github.event.inputs.selected == "All"
    needs: [ config ]
    runs-on: ubuntu-latest
    environment: deploy-all
    strategy:
      matrix:
        company: ${{ fromJSON(needs.config.outputs.matrix) }}
    name: Deploy for ${{ matrix.company.id }}
    steps:
      - name: Deploy
        run: |
          echo "ID: ${{ matrix.company.id }}"
          echo "Company Title: ${{ matrix.company.title }}"
          echo "Company Logo: ${{ matrix.company.logo }}"