name: Matrix with two jobs

on:
  workflow_dispatch:

env:
  GLOBAL_MATRIX: 'GLOBAL-MATRIX'

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: build-matrix
        env:
          LOCAL_MATRIX: 'LOCAL-MATRIX'
        run: |
          echo "GLOBAL_MATRIX=${{ env.GLOBAL_MATRIX }}"
          echo "LOCAL_MATRIX=${{ env.LOCAL_MATRIX }}"
          echo "matrix=HELLO-WORLD" >> "$GITHUB_OUTPUT"  

  deploy-one:
    needs: [ config ]
    runs-on: ubuntu-latest
    environment: deploy-one
    steps:
      - run: echo "matrix=${{ needs.config.outputs.matrix }}"

  deploy-all:
    needs: [ config ]
    runs-on: ubuntu-latest
    environment: deploy-all
    steps:
      - run: echo "matrix=${{ needs.config.outputs.matrix }}"