name: Matrix-2

on:
  workflow_dispatch:

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      company: ${{ steps.vars.outputs.company }}
    steps:
      - name: Collect workflow vars
        id: vars
        run: echo "company=Hello world" >> "$GITHUB_OUTPUT"

  deploy:
    needs: [config]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "test=${{ needs.config.outputs.company }}"