name: Matrix with two jobs

on:
  workflow_dispatch:

env:
  MATRIX: |
    [
      {"id": "company-001", "title": "Company-001", "logo": "logo001.png"},
      {"id": "company-002", "title": "Company-002", "logo": "logo002.png"},
      {"id": "company-003", "title": "Company-003", "logo": "logo003.png"}
    ]

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: build-matrix
        run: |
          echo "::$(echo "${MATRIX}" | jq -c '.')::"
#          cat matrix.json
#          MATRIX_JSON=$(cat matrix.json)
#          echo "matrix=${MATRIX_JSON}" >> "$GITHUB_OUTPUT"
#          echo "matrix=HELLO-WORLD" >> "$GITHUB_OUTPUT"

#  deploy-one:
#    needs: [ config ]
#    runs-on: ubuntu-latest
#    environment: deploy-one
#    steps:
#      - run: |
#          echo "matrix=${{ needs.config.outputs.matrix }}"
#          echo "matrix=${{ fromJSON(needs.config.outputs.matrix) }}"