name: Self hosted runner // ENV and SECRET

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print environment variables
        run: printenv | sort
        env:
          TEST_VAR: ${{ vars.TEST_VAR }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}