name: Self hosted runner // ENV and SECRET

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Enable Debug Mode
        run: set -x

      - name: Print environment variable
        run: echo "TEST_VAR is ${{ vars.TEST_VAR }}"

      - name: Print secret variable
        run: echo "TEST_SECRET is ${{ secrets.TEST_SECRET }}"