name: Self hosted runner // Matrix

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        job_id: [1, 2, 3]
    steps:
      - name: Starting Job ${{ matrix.job_id }}
        run: echo "Starting Job ${{ matrix.job_id }}"

      - name: Wait for 1 minute
        run: sleep 60

      - name: Finishing Job ${{ matrix.job_id }}
        run: echo "Finishing Job ${{ matrix.job_id }}"