name: Three jobs

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Configure"

  build:
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - run: echo "Build"

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "Test"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - run: echo "Deploy"
