name: Three jobs

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Configure"

  build:
    runs-on: ubuntu-latest
#    environment: env_1
    needs:
      - configure
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-002',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-003',  title: 'Company-003', logo: 'logo003.png' }
    steps:
      - run: echo "Deploy ${{ matrix.company.id }}"

  deploy:
    runs-on: ubuntu-20.04
#    environment: env_2
    needs:
      - configure
    strategy:
      max-parallel: 1
      matrix:
        company:
          - { id: 'company-001',  title: 'Company-001', logo: 'logo001.png' }
          - { id: 'company-002',  title: 'Company-002', logo: 'logo002.png' }
          - { id: 'company-003',  title: 'Company-003', logo: 'logo003.png' }
    steps:
      - run: echo "Deploy ${{ matrix.company.id }}"