name: Three jobs

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Configure"

  build:
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - run: echo "Build"

  deploy:
    if: ${{ 'true' == 'false' }}
    runs-on: ubuntu-latest
    needs:
      - configure
    steps:
      - run: echo "Deploy"